create extension if not exists pgcrypto;

create table if not exists public.site_analytics (
    id bigint generated by default as identity primary key,
    site_id uuid not null,
    session_id uuid not null,
    version text not null default 'A' check (version in ('A', 'B')),
    event_type text not null default 'session' check (event_type in ('session', 'page_view', 'click', 'conversion')),
    device_type text not null check (device_type in ('mobile', 'tablet', 'desktop')),
    element_clicked text,
    is_conversion boolean not null default false,
    duration_seconds integer not null default 0 check (duration_seconds >= 0),
    scroll_depth integer not null default 0 check (scroll_depth between 0 and 100),
    created_at timestamptz not null default now()
);

create index if not exists site_analytics_site_created_idx
    on public.site_analytics (site_id, created_at desc);

alter table public.site_analytics
    add column if not exists version text not null default 'A';
alter table public.site_analytics
    add column if not exists event_type text not null default 'session';

create table if not exists public.site_versions (
    version_id uuid primary key default gen_random_uuid(),
    site_id uuid not null,
    html_code text not null,
    status text not null check (status in ('live', 'testing', 'archived')),
    conversion_rate double precision not null default 0,
    created_at timestamptz not null default now()
);

create index if not exists site_versions_site_status_idx
    on public.site_versions (site_id, status, created_at desc);

alter table public.site_analytics enable row level security;
alter table public.site_versions enable row level security;

-- Browser clients never access these tables directly. The generated Vercel API
-- and the Streamlit backend use SUPABASE_SERVICE_ROLE_KEY server-side.